import type { Metadata } from "next";
import "./globals.css";
//import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { QueryClientProvider } from "@/provider/query-client-provider";

export const metadata: Metadata = {
  title: "Movie App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#020916] text-white`}>
        <QueryClientProvider>
          {/* <Header /> */}
          <header className="">
            <Navbar />
          </header>
          {children}
          <Footer />
        </QueryClientProvider>
      </body>
    </html>
  );
}
